### ISSUE TITLE
Phrasing for #7 is unclear, or the accepted answer is incorrect. 

### ISSUE THREAD

**Issue by ddeleon267** [learn-co-students/programming-univbasics-3-quiz-online-web-prework#1]
A previous lesson states that "An argument is the value you pass to a method when you call the method.", but if the student answers "True" to #7 ("An argument is a value that the method expects you to pass when you call it."), it is marked incorrect. Either the accepted answer is incorrect, or the statement needs to be reworded for clarity.  It also should be "An argument" in the quiz, rather than "A argument."

**Comment by sgharms** [comment]
You're right! We've made the change upstream.

This issue was opened on the learn-co-students repo so we didn't see it! Be sure to follow the flag link in Learn to make sure we see the issue!
